---
name: Jekyll CI

on:
  push:
    branches:
      - master

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Deploy to GitHub Pages
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          BUILD_DIR: ${{ secrets.BUILD_DIR }}
          REMOTE_BRANCH: ${{ secrets.REMOTE_BRANCH }}
        uses: burden/jekyll-deploy-gh-pages@master